apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # lables of deployment resource
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: balaguru20/app1:1.0.0 # /repo/dockerfiles\DEPLOYMENT\Dockerfile
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    # aws certificate manger ARN
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:314146304089:certificate/d095163b-8397-4678-a249-75ff0aaba0b4
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: nginx-example
  rules:
  - http:
    paths:
    - path: /testpath
      pahtType: Prefix
      backend:
        service:
          name: test
          port:
            number: 80